language: python

os:
  - linux
  - osx

python:
  - 3.3
  - 3.4

addons:
  apt:
    packages:
      - cmake
      - pip3

install:
    - git clone https://github.com/RoaringBitmap/CRoaring.git
    - cd CRoaring && mkdir -p build && cd build && cmake .. && make && cd ../..
    - export LD_LIBRARY_PATH=CRoaring/build:$LD_LIBRARY_PATH
    - pip3 install  --user hypothesis

script:
  - ./test.py
